version: 40
jobs:
- name: Mirror GitHub
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/DennisBecker/jeditempel-web
    passwordSecret: access-token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALWAYS
    optional: false
  - !PushRepository
    name: push
    remoteUrl: https://github.com/DennisBecker/jeditempel-web
    passwordSecret: access-token
    force: false
    condition: ALWAYS
    optional: false
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0/10 * ? * *
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Deploy
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALWAYS
    optional: false
  - !GenerateChecksumStep
    name: generate package checksum
    files: package-lock.json
    targetFile: checksum
    condition: SUCCESSFUL
    optional: false
  - !SetupCacheStep
    name: set up npm cache
    key: node_modules_@file:checksum@
    loadKeys:
    - node_modules
    paths:
    - node_modules
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: build astro page
    runInContainer: true
    image: node:current-alpine
    interpreter: !DefaultInterpreter
      commands: |
        export NODE_OPTIONS=--max_old_space_size=4096
        npm ci

        PUBLIC_BASE_URL=@property:api-base-url@ npm run build

        node_modules/.bin/netlify deploy --no-build --prod --auth @secret:netlify-token@ --site batallion --dir dist
    useTTY: false
    condition: ALWAYS
    optional: false
  - !CommandStep
    name: deploy to netlify
    runInContainer: true
    image: node:current-alpine
    interpreter: !DefaultInterpreter
      commands: |
        node_modules/.bin/netlify deploy --no-build --prod --auth @secret:netlify-token@ --site batallion --dir dist
    useTTY: true
    condition: NEVER
    optional: false
  paramSpecs:
  - !TextParam
    name: timestamp
    description: force trigger new build
    allowEmpty: false
    multiline: false
    defaultValueProvider: !SpecifiedDefaultValue
      value: '1'
  triggers:
  - !BranchUpdateTrigger
    branches: main
    paths: src/**
    projects: DennisBecker/jeditempel-web
    paramMatrix:
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '1'
      name: timestamp
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
