version: 33
jobs:
- name: Mirror GitHub
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/DennisBecker/jeditempel-web
    passwordSecret: access-token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALWAYS
  - !PushRepository
    name: push
    remoteUrl: https://github.com/DennisBecker/jeditempel-web
    passwordSecret: access-token
    force: false
    condition: ALWAYS
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0/10 * ? * *
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Deploy
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build and deploy
    runInContainer: true
    image: node:current-alpine
    interpreter: !DefaultInterpreter
      commands: |
        npm install

         PUBLIC_BASE_URL=@property:api-base-url@ npm run build

        node_modules/.bin/netlify deploy --prod --auth @secret:netlify-token@ --site jeditempel
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: timestamp
    description: force trigger new build
    allowEmpty: false
    multiline: false
    defaultValueProvider: !SpecifiedDefaultValue
      value: '1'
  triggers:
  - !BranchUpdateTrigger
    branches: main
    paths: src/**
    projects: DennisBecker/jeditempel-web
    paramMatrix:
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '1'
      name: timestamp
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
