version: 26
jobs:
- name: Mirror GitHub
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/DennisBecker/jeditempel-web
    passwordSecret: access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/DennisBecker/jeditempel-web
    syncToChildProject: false
    passwordSecret: access-token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0/10 * ? * *
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
